apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        env: dev
      - cluster: test
        url: https://foo.test.cluster
        env: test
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
                - dev
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
                - test
          maxUpdate: 10%
  template:
    metadata:
      name: '{{cluster}}-guestbook'
      labels:
        envLabel: '{{env}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: master
        path: helm-guestbook
        helm:
          values: |
            replicaCount: 2
            image:
              tag: 0.1
      destination:
        server: "{{url}}"
        namespace: guestbook
          